version: "3.9"

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node-modules:/app/node_modules
    depends_on:
      - "backend"

  backend:
    build:
      context: ./mysite
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "8000:8000"
    # volumes:
    #   - ./backend/:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - db
volumes:
  postgres_data:
  node-modules:
